# dsh-ask bash integration; generated by dsh-ask init bash.
# Set DSH_ASK_PROFILE before starting Bash to use a non-default profile name.
# Source this file from ~/.bashrc after any distribution command-not-found setup.

# This integration is meaningful only in interactive Bash sessions.
[[ $- == *i* ]] || return 0

# Preserve an existing handler once, so re-sourcing this file does not wrap our
# own handler. `declare -f` only reads the current shell's trusted definition.
if ! declare -F __dsh_ask_previous_command_not_found_handle >/dev/null 2>&1; then
    if declare -F command_not_found_handle >/dev/null 2>&1; then
        __dsh_ask_bash_definition=$(declare -f command_not_found_handle) || return 0
        eval "${__dsh_ask_bash_definition/command_not_found_handle/__dsh_ask_previous_command_not_found_handle}"
        unset __dsh_ask_bash_definition
    fi
fi

__dsh_ask_bash_fallback() {
    if declare -F __dsh_ask_previous_command_not_found_handle >/dev/null 2>&1; then
        __dsh_ask_previous_command_not_found_handle "$@"
        return $?
    fi

    return 127
}

command_not_found_handle() {
    local ask_profile
    local argument

    (( $# > 0 )) || return 127

    for argument in "$@"; do
        [[ $argument == *$'\n'* || $argument == *$'\r'* ]] && return 127
    done

    # Do not nest an ask run inside an existing DSH-managed shell.
    if [[ -n ${DSH_SHELL+x} ]]; then
        __dsh_ask_bash_fallback "$@"
        return $?
    fi

    if ! command -v dsh >/dev/null 2>&1; then
        __dsh_ask_bash_fallback "$@"
        return $?
    fi

    ask_profile=${DSH_ASK_PROFILE:-ask}
    DSH_SHELL=1 command dsh --profile "$ask_profile" -- "$@"
    return $?
}
