# dsh-ask fish integration; generated by dsh-ask init fish.
# Set DSH_ASK_PROFILE before starting Fish to use a non-default profile name.

if functions -q fish_command_not_found; and not functions -q __dsh_ask_previous_command_not_found
    functions -c fish_command_not_found __dsh_ask_previous_command_not_found
end

function fish_command_not_found
    status is-interactive; or return 127

    set -l command $argv
    if test (count $command) -eq 0
        return 127
    end

    set -l text (string join ' ' -- $command)
    string match -qr '[\n\r]' -- $text; and return 127

    # Do not nest an ask run inside an existing DSH-managed shell.
    if set -q DSH_SHELL
        return 127
    end

    if command -q dsh
        set -l ask_profile ask
        set -q DSH_ASK_PROFILE; and set ask_profile $DSH_ASK_PROFILE
        command dsh --profile $ask_profile -- $text
        return $status
    end

    if functions -q __dsh_ask_previous_command_not_found
        __dsh_ask_previous_command_not_found $argv
        return $status
    end

    return 127
end
