# dsh-ask PowerShell integration; generated by dsh-ask init powershell.
# Experimental: test this template with every PowerShell host you use.
# Dot-source this file from an interactive $PROFILE after other integrations.

# PowerShell has no fully portable interactive-session predicate. This guards
# obvious non-interactive hosts but does not replace host-specific testing.
if ([Environment]::UserInteractive) {
    # Keep the installation-time handler as a fallback. Do not overwrite this
    # snapshot when the file is dot-sourced again in the same session.
    if ($null -eq (Get-Variable -Name __DshAskPreviousCommandNotFoundAction -Scope Global -ErrorAction SilentlyContinue)) {
        $global:__DshAskPreviousCommandNotFoundAction =
            $ExecutionContext.InvokeCommand.CommandNotFoundAction
    }

    $global:__DshAskCommandNotFoundAction = [System.EventHandler[System.Management.Automation.CommandLookupEventArgs]] {
        param($sender, $eventArgs)

        $previous = $global:__DshAskPreviousCommandNotFoundAction
        if (
            $null -eq $eventArgs -or
            $null -ne $env:DSH_SHELL -or
            -not [Environment]::UserInteractive
        ) {
            if ($null -ne $previous) {
                $previous.Invoke($sender, $eventArgs)
            }
            return
        }

        $dsh = Get-Command dsh -CommandType Application -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if (
            $null -eq $dsh -or
            [string]::IsNullOrWhiteSpace($dsh.Path) -or
            -not ($eventArgs.PSObject.Properties.Name -contains 'CommandName') -or
            -not ($eventArgs.PSObject.Properties.Name -contains 'CommandScriptBlock') -or
            [string]::IsNullOrWhiteSpace($eventArgs.CommandName)
        ) {
            if ($null -ne $previous) {
                $previous.Invoke($sender, $eventArgs)
            }
            return
        }

        # CommandScriptBlock receives the original unresolved command's
        # arguments through $args when PowerShell invokes the replacement.
        $commandName = [string] $eventArgs.CommandName
        $askProfile = if ([string]::IsNullOrWhiteSpace($env:DSH_ASK_PROFILE)) {
            'ask'
        }
        else {
            $env:DSH_ASK_PROFILE
        }
        $dshPath = $dsh.Path

        $eventArgs.CommandScriptBlock = {
            $parts = @($commandName)
            foreach ($argument in $args) {
                $parts += [string] $argument
            }
            $text = $parts -join ' '
            if ([string]::IsNullOrWhiteSpace($text) -or $text -match "[`r`n]") {
                return
            }

            # Set DSH_SHELL only for the child dsh process, then restore the
            # current PowerShell environment even when dsh exits with an error.
            $hadDshShell = Test-Path Env:DSH_SHELL
            $oldDshShell = $env:DSH_SHELL
            try {
                $env:DSH_SHELL = '1'
                & $dshPath --profile $askProfile -- $text
            }
            finally {
                if ($hadDshShell) {
                    $env:DSH_SHELL = $oldDshShell
                }
                else {
                    Remove-Item Env:DSH_SHELL -ErrorAction SilentlyContinue
                }
            }
        }.GetNewClosure()
    }

    $ExecutionContext.InvokeCommand.CommandNotFoundAction =
        $global:__DshAskCommandNotFoundAction
}
