# dsh-ask zsh integration; generated by dsh-ask init zsh.
# Set DSH_ASK_PROFILE before starting Zsh to use a non-default profile name.
# Source this file from ~/.zshrc after framework and command-not-found setup.

# This integration is meaningful only in interactive Zsh sessions.
[[ -o interactive ]] || return 0

# Preserve an existing handler once, so re-sourcing this file does not wrap our
# own handler. `functions` only reads the current shell's trusted definition.
if (( ! $+functions[__dsh_ask_previous_command_not_found_handler] )); then
    if (( $+functions[command_not_found_handler] )); then
        typeset -g __dsh_ask_zsh_definition
        __dsh_ask_zsh_definition="$(functions command_not_found_handler)"
        eval "${__dsh_ask_zsh_definition/command_not_found_handler/__dsh_ask_previous_command_not_found_handler}"
        unset __dsh_ask_zsh_definition
    fi
fi

__dsh_ask_zsh_fallback() {
    if (( $+functions[__dsh_ask_previous_command_not_found_handler] )); then
        __dsh_ask_previous_command_not_found_handler "$@"
        return $?
    fi

    return 127
}

function command_not_found_handler() {
    local ask_profile
    local argument

    (( $# > 0 )) || return 127

    for argument in "$@"; do
        [[ $argument == *$'\n'* || $argument == *$'\r'* ]] && return 127
    done

    # Do not nest an ask run inside an existing DSH-managed shell.
    if [[ -n ${DSH_SHELL+x} ]]; then
        __dsh_ask_zsh_fallback "$@"
        return $?
    fi

    if ! command -v dsh >/dev/null 2>&1; then
        __dsh_ask_zsh_fallback "$@"
        return $?
    fi

    ask_profile=${DSH_ASK_PROFILE:-ask}
    DSH_SHELL=1 command dsh --profile "$ask_profile" -- "$@"
    return $?
}
